### PR TITLE
fix(aiohttp): compatible with non aiohttp projects

### PR DESCRIPTION
**Pull request by LKI**

### CODE REVIEW

**Comment by h2non** [comment]
This should not be necessary. What Python runtime are you using?

**Comment by LKI** [comment]
I use python 3.7.5 (on Windows), here are some info may helps:

```
$ python --version 
Python 3.7.5

$ pip list 
Package    Version
---------- -------
pip        20.0.2
setuptools 46.1.1
wheel      0.34.2

$ python 
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiohttp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by h2non** [comment]
Ok, I got it. I have added a small change to make the linter pass. I will merge afterward.

**Comment by LKI** [comment]
Thanks~

**Comment by h2non** [comment]
New version `v1.0.1` is now available on PyPI:
`pip install --upgrade pook`

**Comment by LKI** [comment]
Cool~ Thanks~

**Pull request merged**
