### PR TITLE
Add support for true binary bodies

### LINKED ISSUE #55: Support binary body such as image

### PR DESCRIPTION
**Pull request by sarayourfriend**
Fixes #55 by adding a flag to mark a body as "binary" and prevent the interceptor and matcher from encoding/decoding bytes objects.

Useful when `.decode('utf-8')` would fail, for example, when using an image's binary data as the response.

To confirm this fix actually works as expected, checkout the branch and update one of the new binary-body unit tests to pass `binary=False` instead. You'll see the error that exists on `main` when attempting to pass non-utf-8 encoded bytes. In this case, `nothing.bin`, added in this PR, is just 1KB of `/udev/random` generated with `dd if=/dev/urandom of=nothing.bin bs=1 count=1024` on my local.

### CODE REVIEW

**Comment by sarayourfriend** [comment]
@h2non Do you think this PR can get a review/is it desired? We'd find this useful on Openverse. I've taken a stab at a relatively non-intrusive implementation, but I'm more than happy to make revisions to it if you disagree with adding new parameters to existing methods. Just let me know either way. We benefit greatly from pook on the Openverse project and this ability would allow us to fully remove the last of our janky requests mocking in favour of the much more pleasant and understandable (and maintainable!) pook approach :slightly_smiling_face:

**Comment by sarayourfriend** [comment]
Hi @h2non, just wanted to check in again about this PR and whether you will be able to review it. As I said, happy to make any changes or take a different approach, if needed.

If you'd like ongoing help maintaining this library (reviewing PRs, triaging issues, etc), I'm happy to also offer my support there, to keep this project moving and able to support the growing Python asyncio ecosystem. If you want to discuss that, the easiest way to get in touch with me is through the [WordPress Make Slack](make.wordpress.org/chat/) or Telegram, which you can find a link to my account for here: https://sarayourfriend.pictures/contact/

Thanks again for the work on this project, it is very much appreciated, and I am keen to see that it continues to get supported with bug fixes and dependency updates as needed (and new features too, as appropriate). Open to discussing any of this with you, in addition to this PR, so just let me know if that's something you're interested in. Thanks!

**Comment by h2non** [comment]
hey @sarayourfriend thanks for your contribution :) 
Happy to hand you over the maintenance of the package, since unfortunately, I have no time. If that works for you, I can invite you as a contributor. Feel free to proceed as you consider best, just keep the spirit of the project alive 👍 ;)

**Comment by sarayourfriend** [comment]
Thanks for review and merge @h2non. If you're comfortable adding me, please go ahead, and let me know how best to coordinate releases etc :pray:

**Comment by h2non** [comment]
@sarayourfriend Invitation sent 👍  
You are welcome to merge PR that passes the bar and prepare new releases, just let me know once a new version is ready and I will publish it on PyPI. You can reach me via email if I'm not responsive on GH, which is usually the case ;)

**Pull request merged**
